import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import NavBarProvider from "./contex/NavBarCont";
import MenuContexProvider from "./contex/MenuContex";
import CartContexProvider from "./contex/CartContex";
import OrderContexProvider from "./contex/OrderContex";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FoodHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <OrderContexProvider>
          {" "}
          <MenuContexProvider>
            <CartContexProvider>
              <NavBarProvider>
                <NavBar />
                {children}
              </NavBarProvider>
            </CartContexProvider>
          </MenuContexProvider>
        </OrderContexProvider>
      </body>
    </html>
  );
}
