import {
  BURGER_IMAGE,
  DESSERT_IMAGE,
  JUICE_IMAGE,
  PASTA_IMAGE,
  PIZZA_IMAGE,
  SALAD_IMAGE,
} from "./images";
const menu = [
  {
    id: 1,
    category: "burger",
    name: "Classic Beef Burger",
    price: 12.99,
    image: BURGER_IMAGE,
    rating: 4.8,
    reviews: 324,
    description: "Juicy grilled beef burger with fresh vegetables and cheese.",
    ingredients: ["Beef Patty", "Bun", "Cheddar Cheese", "Lettuce", "Tomato"],
    nutrition: { calories: 650, protein: "35g", carbs: "42g", fat: "38g" },
  },
  {
    id: 2,
    category: "burger",
    name: "BBQ Bacon Burger",
    price: 14.99,
    image: BURGER_IMAGE,
    rating: 4.9,
    reviews: 512,
    description: "Beef burger topped with crispy bacon and BBQ sauce.",
    ingredients: ["Beef Patty", "Bacon", "BBQ Sauce", "Cheddar Cheese", "Bun"],
    nutrition: { calories: 780, protein: "42g", carbs: "45g", fat: "48g" },
  },
  {
    id: 3,
    category: "burger",
    name: "Mushroom Swiss Burger",
    price: 13.99,
    image: BURGER_IMAGE,
    rating: 4.7,
    reviews: 276,
    description: "Beef burger with sautéed mushrooms and Swiss cheese.",
    ingredients: ["Beef Patty", "Swiss Cheese", "Mushrooms", "Bun"],
    nutrition: { calories: 710, protein: "38g", carbs: "40g", fat: "43g" },
  },
  {
    id: 4,
    category: "burger",
    name: "Spicy Jalapeno Burger",
    price: 13.99,
    image: BURGER_IMAGE,
    rating: 4.7,
    reviews: 245,
    description:
      "Spicy beef burger loaded with jalapenos and pepper jack cheese.",
    ingredients: ["Beef Patty", "Jalapenos", "Pepper Jack Cheese", "Bun"],
    nutrition: { calories: 720, protein: "39g", carbs: "41g", fat: "44g" },
  },
  {
    id: 5,
    category: "burger",
    name: "Double Cheese Burger",
    price: 15.99,
    image: BURGER_IMAGE,
    rating: 4.9,
    reviews: 532,
    description: "Double beef patties layered with melted cheddar cheese.",
    ingredients: ["Double Beef", "Cheddar Cheese", "Bun"],
    nutrition: { calories: 850, protein: "48g", carbs: "44g", fat: "55g" },
  },
  {
    id: 6,
    category: "burger",
    name: "Chicken Burger Deluxe",
    price: 12.49,
    image: BURGER_IMAGE,
    rating: 4.6,
    reviews: 198,
    description: "Crispy chicken burger served with lettuce and mayo.",
    ingredients: ["Chicken", "Lettuce", "Mayonnaise", "Bun"],
    nutrition: { calories: 620, protein: "34g", carbs: "46g", fat: "30g" },
  },
  {
    id: 7,
    category: "burger",
    name: "Mushroom Bacon Burger",
    price: 15.49,
    image: BURGER_IMAGE,
    rating: 4.8,
    reviews: 311,
    description: "Beef burger with bacon, mushrooms and Swiss cheese.",
    ingredients: ["Beef", "Bacon", "Mushroom", "Swiss Cheese"],
    nutrition: { calories: 790, protein: "43g", carbs: "42g", fat: "50g" },
  },
  {
    id: 8,
    category: "burger",
    name: "Smoky BBQ Burger",
    price: 14.49,
    image: BURGER_IMAGE,
    rating: 4.8,
    reviews: 275,
    description: "Smoked beef burger topped with BBQ sauce and onions.",
    ingredients: ["Beef", "BBQ Sauce", "Onions", "Bun"],
    nutrition: { calories: 730, protein: "40g", carbs: "43g", fat: "46g" },
  },
  {
    id: 9,
    category: "burger",
    name: "Avocado Burger",
    price: 14.99,
    image: BURGER_IMAGE,
    rating: 4.5,
    reviews: 176,
    description: "Fresh avocado slices with juicy grilled beef.",
    ingredients: ["Beef", "Avocado", "Lettuce", "Bun"],
    nutrition: { calories: 680, protein: "35g", carbs: "40g", fat: "42g" },
  },
  {
    id: 10,
    category: "burger",
    name: "Mega Beef Burger",
    price: 17.99,
    image: BURGER_IMAGE,
    rating: 4.9,
    reviews: 604,
    description: "Large double-layer beef burger for serious appetite.",
    ingredients: ["Double Beef", "Cheese", "Tomato", "Lettuce"],
    nutrition: { calories: 950, protein: "56g", carbs: "48g", fat: "60g" },
  },

  {
    id: 11,
    category: "pizza",
    name: "Margherita Pizza",
    price: 13.99,
    image: PIZZA_IMAGE,
    rating: 4.6,
    reviews: 198,
    description: "Classic pizza with mozzarella cheese and basil.",
    ingredients: ["Pizza Dough", "Tomato Sauce", "Mozzarella", "Basil"],
    nutrition: { calories: 540, protein: "22g", carbs: "60g", fat: "22g" },
  },
  {
    id: 12,
    category: "pizza",
    name: "Pepperoni Pizza",
    price: 15.99,
    image: PIZZA_IMAGE,
    rating: 4.9,
    reviews: 643,
    description: "Loaded with pepperoni slices and mozzarella cheese.",
    ingredients: ["Pizza Dough", "Pepperoni", "Mozzarella", "Tomato Sauce"],
    nutrition: { calories: 670, protein: "28g", carbs: "62g", fat: "32g" },
  },
  {
    id: 13,
    category: "pizza",
    name: "Chicken Ranch Pizza",
    price: 16.99,
    image: PIZZA_IMAGE,
    rating: 4.8,
    reviews: 421,
    description: "Tender chicken with creamy ranch dressing.",
    ingredients: ["Pizza Dough", "Chicken", "Ranch Sauce", "Mozzarella"],
    nutrition: { calories: 690, protein: "35g", carbs: "58g", fat: "30g" },
  },
  {
    id: 14,
    category: "pizza",
    name: "BBQ Chicken Pizza",
    price: 17.99,
    image: PIZZA_IMAGE,
    rating: 4.8,
    reviews: 376,
    description: "Pizza topped with grilled chicken and BBQ sauce.",
    ingredients: ["Chicken", "BBQ Sauce", "Mozzarella"],
    nutrition: { calories: 690, protein: "34g", carbs: "59g", fat: "31g" },
  },
  {
    id: 15,
    category: "pizza",
    name: "Vegetarian Pizza",
    price: 14.99,
    image: PIZZA_IMAGE,
    rating: 4.4,
    reviews: 163,
    description: "Loaded with fresh vegetables and mozzarella cheese.",
    ingredients: ["Bell Pepper", "Onion", "Olives", "Mozzarella"],
    nutrition: { calories: 520, protein: "18g", carbs: "63g", fat: "19g" },
  },
  {
    id: 16,
    category: "pizza",
    name: "Meat Lovers Pizza",
    price: 18.99,
    image: PIZZA_IMAGE,
    rating: 4.9,
    reviews: 590,
    description: "Packed with beef, sausage and pepperoni.",
    ingredients: ["Beef", "Pepperoni", "Sausage", "Cheese"],
    nutrition: { calories: 780, protein: "40g", carbs: "65g", fat: "38g" },
  },
  {
    id: 17,
    category: "pizza",
    name: "Four Cheese Pizza",
    price: 16.49,
    image: PIZZA_IMAGE,

    rating: 4.7,
    reviews: 281,
    description: "Blend of mozzarella, cheddar, parmesan and gouda.",
    ingredients: ["Mozzarella", "Cheddar", "Parmesan", "Gouda"],
    nutrition: { calories: 700, protein: "29g", carbs: "60g", fat: "35g" },
  },
  {
    id: 18,
    category: "pizza",
    name: "Seafood Pizza",
    price: 19.99,
    image: PIZZA_IMAGE,
    rating: 4.6,
    reviews: 214,
    description: "Fresh shrimp and seafood on crispy pizza crust.",
    ingredients: ["Shrimp", "Calamari", "Mozzarella"],
    nutrition: { calories: 670, protein: "36g", carbs: "57g", fat: "28g" },
  },
  {
    id: 19,
    category: "pizza",
    name: "Spicy Pepperoni Pizza",
    price: 17.49,
    image: PIZZA_IMAGE,
    rating: 4.8,
    reviews: 445,
    description: "Pepperoni pizza with extra chili flakes.",
    ingredients: ["Pepperoni", "Cheese", "Chili Flakes"],
    nutrition: { calories: 710, protein: "30g", carbs: "62g", fat: "34g" },
  },
  {
    id: 20,
    category: "pizza",
    name: "Buffalo Chicken Pizza",
    price: 18.49,
    image: PIZZA_IMAGE,
    rating: 4.7,
    reviews: 295,
    description: "Buffalo chicken with creamy cheese topping.",
    ingredients: ["Chicken", "Buffalo Sauce", "Mozzarella"],
    nutrition: { calories: 720, protein: "33g", carbs: "61g", fat: "35g" },
  },
  {
    id: 21,
    category: "pasta",
    name: "Alfredo Pasta",
    price: 13.99,
    image: PASTA_IMAGE,
    rating: 4.5,
    reviews: 185,
    description: "Creamy Alfredo sauce with parmesan cheese.",
    ingredients: ["Pasta", "Cream", "Parmesan", "Butter"],
    nutrition: { calories: 620, protein: "20g", carbs: "68g", fat: "28g" },
  },
  {
    id: 22,
    category: "pasta",
    name: "Spaghetti Bolognese",
    price: 14.99,
    image: PASTA_IMAGE,
    rating: 4.8,
    reviews: 389,
    description: "Traditional Italian pasta with meat sauce.",
    ingredients: ["Spaghetti", "Ground Beef", "Tomato Sauce", "Onion"],
    nutrition: { calories: 700, protein: "32g", carbs: "72g", fat: "24g" },
  },
  {
    id: 23,
    category: "pasta",
    name: "Seafood Pasta",
    price: 17.99,
    image: PASTA_IMAGE,
    rating: 4.7,
    reviews: 248,
    description: "Fresh shrimp and calamari in garlic sauce.",
    ingredients: ["Pasta", "Shrimp", "Calamari", "Garlic", "Olive Oil"],
    nutrition: { calories: 650, protein: "36g", carbs: "66g", fat: "20g" },
  },
  {
    id: 24,
    category: "pasta",
    name: "Chicken Pesto Pasta",
    price: 15.99,
    image: PASTA_IMAGE,
    rating: 4.8,
    reviews: 302,
    description: "Grilled chicken mixed with creamy pesto sauce.",
    ingredients: ["Pasta", "Chicken", "Pesto", "Parmesan"],
    nutrition: { calories: 690, protein: "38g", carbs: "63g", fat: "26g" },
  },
  {
    id: 25,
    category: "pasta",
    name: "Mac and Cheese",
    price: 12.99,
    image: PASTA_IMAGE,
    rating: 4.6,
    reviews: 214,
    description: "Classic macaroni loaded with rich cheese sauce.",
    ingredients: ["Macaroni", "Cheddar", "Milk", "Butter"],
    nutrition: { calories: 640, protein: "22g", carbs: "70g", fat: "29g" },
  },
  {
    id: 26,
    category: "pasta",
    name: "Lasagna",
    price: 16.99,
    image: PASTA_IMAGE,
    rating: 4.9,
    reviews: 410,
    description: "Layered pasta with beef and creamy béchamel sauce.",
    ingredients: ["Lasagna Sheets", "Beef", "Cheese", "Sauce"],
    nutrition: { calories: 760, protein: "40g", carbs: "68g", fat: "35g" },
  },
  {
    id: 27,
    category: "pasta",
    name: "Shrimp Alfredo",
    price: 18.49,
    image: PASTA_IMAGE,
    rating: 4.8,
    reviews: 276,
    description: "Creamy Alfredo pasta with grilled shrimp.",
    ingredients: ["Pasta", "Shrimp", "Cream", "Parmesan"],
    nutrition: { calories: 720, protein: "39g", carbs: "64g", fat: "31g" },
  },
  {
    id: 28,
    category: "pasta",
    name: "Vegetable Pasta",
    price: 13.49,
    image: PASTA_IMAGE,
    rating: 4.4,
    reviews: 165,
    description: "Healthy pasta with seasonal vegetables.",
    ingredients: ["Pasta", "Broccoli", "Carrot", "Bell Pepper"],
    nutrition: { calories: 560, protein: "16g", carbs: "74g", fat: "18g" },
  },
  {
    id: 29,
    category: "pasta",
    name: "Creamy Mushroom Pasta",
    price: 14.99,
    image: PASTA_IMAGE,
    rating: 4.7,
    reviews: 228,
    description: "Pasta tossed in rich mushroom cream sauce.",
    ingredients: ["Pasta", "Mushrooms", "Cream", "Parmesan"],
    nutrition: { calories: 630, protein: "21g", carbs: "69g", fat: "27g" },
  },
  {
    id: 30,
    category: "pasta",
    name: "Spicy Arrabbiata Pasta",
    price: 14.49,
    image: PASTA_IMAGE,
    rating: 4.6,
    reviews: 191,
    description: "Italian spicy tomato sauce with fresh herbs.",
    ingredients: ["Pasta", "Tomato Sauce", "Chili", "Garlic"],
    nutrition: { calories: 590, protein: "18g", carbs: "76g", fat: "16g" },
  },

  {
    id: 31,
    category: "juice",
    name: "Mango Juice",
    price: 4.99,
    image: JUICE_IMAGE,
    rating: 4.6,
    reviews: 157,
    description: "Fresh mango juice with natural sweetness.",
    ingredients: ["Mango", "Water", "Ice"],
    nutrition: { calories: 180, protein: "2g", carbs: "42g", fat: "0g" },
  },
  {
    id: 32,
    category: "juice",
    name: "Orange Juice",
    price: 3.99,
    image: JUICE_IMAGE,
    rating: 4.9,
    reviews: 534,
    description: "Freshly squeezed oranges rich in vitamin C.",
    ingredients: ["Orange"],
    nutrition: { calories: 140, protein: "2g", carbs: "33g", fat: "0g" },
  },
  {
    id: 33,
    category: "juice",
    name: "Strawberry Juice",
    price: 4.99,
    image: JUICE_IMAGE,
    rating: 4.7,
    reviews: 213,
    description: "Refreshing strawberry drink with ice.",
    ingredients: ["Strawberries", "Water", "Ice"],
    nutrition: { calories: 160, protein: "1g", carbs: "38g", fat: "0g" },
  },
  {
    id: 34,
    category: "juice",
    name: "Pineapple Juice",
    price: 4.49,
    image: JUICE_IMAGE,
    rating: 4.5,
    reviews: 178,
    description: "Fresh pineapple juice served chilled.",
    ingredients: ["Pineapple", "Ice"],
    nutrition: { calories: 170, protein: "1g", carbs: "40g", fat: "0g" },
  },
  {
    id: 35,
    category: "juice",
    name: "Watermelon Juice",
    price: 4.49,
    image: JUICE_IMAGE,
    rating: 4.8,
    reviews: 240,
    description: "Cool watermelon drink perfect for summer.",
    ingredients: ["Watermelon", "Ice"],
    nutrition: { calories: 130, protein: "1g", carbs: "31g", fat: "0g" },
  },
  {
    id: 36,
    category: "juice",
    name: "Kiwi Juice",
    price: 5.49,
    image: JUICE_IMAGE,
    rating: 4.4,
    reviews: 122,
    description: "Tangy kiwi juice packed with vitamins.",
    ingredients: ["Kiwi", "Water", "Ice"],
    nutrition: { calories: 150, protein: "2g", carbs: "35g", fat: "0g" },
  },
  {
    id: 37,
    category: "juice",
    name: "Apple Juice",
    price: 3.99,
    image: JUICE_IMAGE,
    rating: 4.7,
    reviews: 287,
    description: "Fresh apple juice with natural flavor.",
    ingredients: ["Apple"],
    nutrition: { calories: 145, protein: "0g", carbs: "34g", fat: "0g" },
  },
  {
    id: 38,
    category: "juice",
    name: "Lemon Mint Juice",
    price: 4.99,
    image: JUICE_IMAGE,
    rating: 4.8,
    reviews: 366,
    description: "Refreshing lemon and mint cooler.",
    ingredients: ["Lemon", "Mint", "Ice"],
    nutrition: { calories: 120, protein: "0g", carbs: "28g", fat: "0g" },
  },
  {
    id: 39,
    category: "juice",
    name: "Mixed Berry Juice",
    price: 5.99,
    image: JUICE_IMAGE,
    rating: 4.9,
    reviews: 305,
    description: "Blend of blueberries, raspberries and strawberries.",
    ingredients: ["Blueberries", "Raspberries", "Strawberries"],
    nutrition: { calories: 190, protein: "2g", carbs: "44g", fat: "0g" },
  },
  {
    id: 40,
    category: "juice",
    name: "Peach Juice",
    price: 4.99,
    image: JUICE_IMAGE,
    rating: 4.6,
    reviews: 189,
    description: "Sweet peach juice served ice cold.",
    ingredients: ["Peach", "Ice"],
    nutrition: { calories: 165, protein: "1g", carbs: "39g", fat: "0g" },
  },
  {
    id: 41,
    category: "salad",
    name: "Caesar Salad",
    price: 10.99,
    image: SALAD_IMAGE,
    rating: 4.4,
    reviews: 145,
    description: "Fresh lettuce with Caesar dressing and croutons.",
    ingredients: ["Romaine Lettuce", "Croutons", "Parmesan", "Caesar Dressing"],
    nutrition: { calories: 320, protein: "12g", carbs: "18g", fat: "22g" },
  },
  {
    id: 42,
    category: "salad",
    name: "Greek Salad",
    price: 10.99,
    image: SALAD_IMAGE,
    rating: 4.5,
    reviews: 178,
    description: "Mediterranean salad with feta cheese and olives.",
    ingredients: ["Tomato", "Cucumber", "Feta Cheese", "Olives"],
    nutrition: { calories: 280, protein: "10g", carbs: "12g", fat: "18g" },
  },
  {
    id: 43,
    category: "salad",
    name: "Chicken Avocado Salad",
    price: 13.99,
    image: SALAD_IMAGE,
    rating: 4.8,
    reviews: 296,
    description: "Grilled chicken served with fresh avocado.",
    ingredients: ["Chicken Breast", "Avocado", "Lettuce", "Tomato"],
    nutrition: { calories: 390, protein: "30g", carbs: "14g", fat: "22g" },
  },
  {
    id: 44,
    category: "salad",
    name: "Garden Salad",
    price: 9.99,
    image: SALAD_IMAGE,
    rating: 4.3,
    reviews: 132,
    description: "Fresh mixed vegetables with light dressing.",
    ingredients: ["Lettuce", "Tomato", "Cucumber", "Carrot"],
    nutrition: { calories: 210, protein: "6g", carbs: "20g", fat: "10g" },
  },
  {
    id: 45,
    category: "salad",
    name: "Tuna Salad",
    price: 12.99,
    image: SALAD_IMAGE,
    rating: 4.6,
    reviews: 205,
    description: "Protein-rich tuna served with crisp vegetables.",
    ingredients: ["Tuna", "Lettuce", "Corn", "Tomato"],
    nutrition: { calories: 350, protein: "28g", carbs: "15g", fat: "16g" },
  },
  {
    id: 46,
    category: "salad",
    name: "Cobb Salad",
    price: 14.49,
    image: SALAD_IMAGE,
    rating: 4.7,
    reviews: 248,
    description: "Classic Cobb salad with chicken, egg and bacon.",
    ingredients: ["Chicken", "Egg", "Bacon", "Lettuce"],
    nutrition: { calories: 420, protein: "34g", carbs: "12g", fat: "24g" },
  },
  {
    id: 47,
    category: "salad",
    name: "Quinoa Salad",
    price: 11.99,
    image: SALAD_IMAGE,
    rating: 4.5,
    reviews: 173,
    description: "Healthy quinoa mixed with vegetables.",
    ingredients: ["Quinoa", "Cucumber", "Tomato", "Parsley"],
    nutrition: { calories: 290, protein: "11g", carbs: "34g", fat: "9g" },
  },
  {
    id: 48,
    category: "salad",
    name: "Shrimp Salad",
    price: 15.99,
    image: SALAD_IMAGE,
    rating: 4.8,
    reviews: 267,
    description: "Fresh shrimp with greens and citrus dressing.",
    ingredients: ["Shrimp", "Lettuce", "Orange", "Dressing"],
    nutrition: { calories: 340, protein: "29g", carbs: "13g", fat: "14g" },
  },
  {
    id: 49,
    category: "salad",
    name: "Asian Chicken Salad",
    price: 13.49,
    image: SALAD_IMAGE,
    rating: 4.6,
    reviews: 219,
    description: "Chicken salad with sesame dressing.",
    ingredients: ["Chicken", "Cabbage", "Carrot", "Sesame"],
    nutrition: { calories: 360, protein: "31g", carbs: "18g", fat: "15g" },
  },
  {
    id: 50,
    category: "salad",
    name: "Avocado Kale Salad",
    price: 12.49,
    image: SALAD_IMAGE,
    rating: 4.4,
    reviews: 154,
    description: "Nutritious kale mixed with creamy avocado.",
    ingredients: ["Kale", "Avocado", "Lemon", "Olive Oil"],
    nutrition: { calories: 300, protein: "8g", carbs: "16g", fat: "20g" },
  },

  {
    id: 51,
    category: "dessert",
    name: "Chocolate Lava Cake",
    price: 8.99,
    image: DESSERT_IMAGE,
    rating: 4.9,
    reviews: 728,
    description: "Warm chocolate cake with a molten center.",
    ingredients: ["Chocolate", "Butter", "Flour", "Eggs"],
    nutrition: { calories: 450, protein: "6g", carbs: "52g", fat: "24g" },
  },
  {
    id: 52,
    category: "dessert",
    name: "New York Cheesecake",
    price: 7.99,
    image: DESSERT_IMAGE,
    rating: 4.8,
    reviews: 615,
    description: "Creamy cheesecake with a buttery crust.",
    ingredients: ["Cream Cheese", "Sugar", "Eggs", "Biscuit Base"],
    nutrition: { calories: 480, protein: "8g", carbs: "45g", fat: "28g" },
  },
  {
    id: 53,
    category: "dessert",
    name: "Tiramisu",
    price: 8.99,
    image: DESSERT_IMAGE,
    rating: 4.7,
    reviews: 342,
    description: "Italian dessert layered with coffee and mascarpone.",
    ingredients: ["Mascarpone", "Coffee", "Ladyfingers", "Cocoa Powder"],
    nutrition: { calories: 420, protein: "7g", carbs: "40g", fat: "22g" },
  },
  {
    id: 54,
    category: "dessert",
    name: "Brownie",
    price: 6.99,
    image: DESSERT_IMAGE,
    rating: 4.8,
    reviews: 401,
    description: "Rich chocolate brownie with soft center.",
    ingredients: ["Chocolate", "Butter", "Sugar", "Flour"],
    nutrition: { calories: 390, protein: "5g", carbs: "48g", fat: "20g" },
  },
  {
    id: 55,
    category: "dessert",
    name: "Apple Pie",
    price: 7.49,
    image: DESSERT_IMAGE,
    rating: 4.6,
    reviews: 238,
    description: "Classic apple pie with cinnamon flavor.",
    ingredients: ["Apple", "Flour", "Butter", "Cinnamon"],
    nutrition: { calories: 370, protein: "4g", carbs: "50g", fat: "16g" },
  },
  {
    id: 56,
    category: "dessert",
    name: "Ice Cream Sundae",
    price: 6.99,
    image: DESSERT_IMAGE,
    rating: 4.9,
    reviews: 517,
    description: "Vanilla ice cream topped with chocolate sauce.",
    ingredients: ["Ice Cream", "Chocolate Sauce", "Cream"],
    nutrition: { calories: 340, protein: "5g", carbs: "38g", fat: "18g" },
  },
  {
    id: 57,
    category: "dessert",
    name: "Red Velvet Cake",
    price: 8.49,
    image: DESSERT_IMAGE,
    rating: 4.8,
    reviews: 329,
    description: "Soft red velvet cake with cream cheese frosting.",
    ingredients: ["Flour", "Cocoa", "Cream Cheese", "Sugar"],
    nutrition: { calories: 460, protein: "6g", carbs: "54g", fat: "23g" },
  },
  {
    id: 58,
    category: "dessert",
    name: "Donuts",
    price: 5.99,
    image: DESSERT_IMAGE,
    rating: 4.5,
    reviews: 284,
    description: "Fresh glazed donuts with sweet topping.",
    ingredients: ["Flour", "Sugar", "Milk", "Butter"],
    nutrition: { calories: 320, protein: "4g", carbs: "42g", fat: "14g" },
  },
  {
    id: 59,
    category: "dessert",
    name: "Chocolate Muffin",
    price: 4.99,
    image: DESSERT_IMAGE,
    rating: 4.7,
    reviews: 193,
    description: "Moist muffin packed with chocolate chips.",
    ingredients: ["Chocolate Chips", "Flour", "Milk", "Eggs"],
    nutrition: { calories: 310, protein: "5g", carbs: "39g", fat: "13g" },
  },
  {
    id: 60,
    category: "dessert",
    name: "Pancake Stack",
    price: 8.99,
    image: DESSERT_IMAGE,
    rating: 4.8,
    reviews: 366,
    description: "Fluffy pancakes served with maple syrup.",
    ingredients: ["Flour", "Milk", "Eggs", "Maple Syrup"],
    nutrition: { calories: 430, protein: "8g", carbs: "58g", fat: "16g" },
  },
];
export default menu;
